In [1]:
import torch

# 创建一个全零的二维张量，形状为 [3, 5]，表示 3 个样本，每个样本有 5 个类别。
tensor = torch.zeros(3, 5)

# 真实标签，表示每个样本所属的类别索引
labels = torch.tensor([1, 3, 4])  # 三个样本的类别分别是 1, 3, 4

# 使用 scatter_ 将每行中指定索引（labels）的值设置为 1
tensor.scatter_(1, labels.view(-1, 1), 1)

print(tensor)
tensor

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [2]:
import torch

# 创建一个全零的二维张量，形状为 [3, 5]，表示 3 个样本，每个样本有 5 个类别。
tensor = torch.zeros(3, 5)

# 真实标签，表示每个样本所属的类别索引
labels = torch.tensor([1, 2, 3])  # 三个样本的类别分别是 1, 3, 4

# 使用 scatter_ 将每行中指定索引（labels）的值设置为 1
tensor.scatter_(1, labels.view(-1, 1), 1)

print(tensor)
tensor

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


tensor([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])